### ISSUE TITLE
 not enough values to unpack (expected 14, got 0)

### ISSUE THREAD

**Issue by shouvik-paul** [masashitsubaki/CPI_human#1]
Traceback (most recent call last):
  File "C:/Users/user/Downloads/15647NeonBand.RarZipExtractorPro_g3b9h1p9bdemw!App/CPI_prediction-master/CPI_prediction-master/code/newtest1.py", line 153., in <module>
    setting) = sys.argv[1:]
ValueError: not enough values to unpack (expected 14, got 0)
################
I am getting this type of error. How can I solve it? Can you provide me the original code to me please....
My email id shouvik28paul@gmail.com

**Comment by masashitsubaki** [comment]
In my environment (Mac or Linux), such error does not occur.

Could you clone this repository (git clone https://github.com/masashitsubaki/CPI_prediction.git) again and run the following two commands: bash preprocess_data.sh and bash run_training.sh in the code directory?

**Comment by shouvik-paul** [comment]
Yes, I have downloaded this repository (git clone https://github.com/masashitsubaki/CPI_prediction.git), downloaded zip file extract it and and run the following two commands: preprocess_data.py and run_training.py in the code directory... 
but I am getting this problem in my Windows environment. 

can you please send me the exact code with all the file location .....
my email id is shouvik28paul@gmail.com

**Comment by masashitsubaki** [comment]
Perhaps, did you run "python run_training.py"  not "bash run_training.sh" ?

**Comment by shouvik-paul** [comment]
I am now trying on Linux.... 
when I run 'bash preprocess_data.sh' , I found some error' no module named rdkit'. 
At first.... 
actually I installed anaconda python and make an environment of 'my-rdkit-env'. 
there i found 'not enough values to unpack (expected 14, got 0)' 

How can I install rdkit without conda? 
kindly send me the full code or send me the .py file .... please... 
shouvik28paul@gmail.com

**Comment by masashitsubaki** [comment]
I do not know the detail about install of RDKit.
I just installed RDKit with 'conda install -c rdkit rdkit'
(see https://anaconda.org/rdkit/rdkit).

**Comment by shouvik-paul** [comment]
please send me the original  .py file to my email shouvik28paul@gmail.com

**Comment by shouvik-paul** [comment]
did you run it on python 3( anaconda 3) or python 2 ?

**Comment by shouvik-paul** [comment]
I installed anaconda python 3.7  and run in the terminal " bash run_training.sh ". 
but I am facing this type of problem.
(base) acer@acer-Aspire-A515-51G:~/Downloads/test/CPI_prediction-master/code$ bash run_training.sh
Traceback (most recent call last):
  File "run_training.py", line 7, in <module>
    import torch
  File "/home/acer/anaconda3/lib/python3.7/site-packages/torch/__init__.py", line 102, in <module>
    from torch._C import *
ImportError: /home/acer/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: nvrtcGetProgramLogSize
(base) acer@acer-Aspire-A515-51G:~/Downloads/test/CPI_prediction-master/code$

**Comment by shouvik-paul** [comment]
Sorry for disturbing you....
Your code is 100% right.
I successfully run it today after installing and uninstalling many dependencies. 
It takes much time to set my environment. 
Thank you very much for your help..... 
actually I want to implement attention based CNN for predicting Protein-Protein Interaction....(Protein-Protein Interaction using attention mechanism, pytorch). 
If you give me some suggestions, I will be very grateful. Thank you once again.

**Comment by kiki-win** [comment]
@shouvik-paul 
Hello, I'm sorry to bother you.
I'm new to programming, and I'm running this code now.
Now I have the same problem as you had.
How did you solve it at that time?
I am looking forward to receiving your reply!

**Comment by kiki-win** [comment]
> 

Hello, did you successfully use the trained model?

**Comment by shouvik-paul** [comment]
> @shouvik-paul Hello, I'm sorry to bother you. I'm new to programming, and I'm running this code now. Now I have the same problem as you had. How did you solve it at that time? I am looking forward to receiving your reply!

Hi @kiki-win 
I have used the Linux environment at the end. I have faced a lot of problems with Windows Environment because of the versions of dependencies. But in Linux environment, I have changed some syntax based on the avaiable versions of that time and succeed. Let me know if it is not solved by you after minor changes in Linux Environment.

**Comment by taopeachzi** [comment]
您好，我使用的是linux环境，麻烦问下您使用的版本是什么嘛，遇到了和您之前一样的问题
