### ISSUE TITLE
Preprocess fails even on original data with original code when simplest "bash preprocess_data.sh" is submitted

### ISSUE THREAD

**Issue by ojovic985** [masashitsubaki/CPI_human#19]
Input (in terminal): .../CPI_prediction/code$ bash preprocess_data.sh

Output: ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6212,) + inhomogeneous part.

Could you please explain this? Or correct this? 

The fact that this kind of output is obtained even on your own original data, is... discouraging, I must say. I admit that I am disappointed.

**Comment by fagehuohuo** [comment]
Hello, perhaps you can adjust the ”numpy “ version， such as numpy==1.21.6 would work.

**Comment by ojovic985** [comment]
So the preprocess works but only if I downgrade numpy to 1.21.6. Then also does the training work. But, one of the consequences is the following: 
tensorflow 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 1.21.6 which is incompatible.
