### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by yvquanli** [masashitsubaki/CPI_human#2]
Thanks for sharing the code!

I read the code carefully, but I found some questions.

- 1 How about the end2end test? what the end2end mean is, that mol and protein in, and interaction out.

- 2 The molecular input without any feature, will it make any sense, with GNN?

- 3 Where is edge features? Description in the paper, but no line in the code.

**Comment by masashitsubaki** [comment]
Sorry for my late reply.

For 1 and 2: The end-to-end learning means that the model does not require any input features (or descriptors), that is, all parameters "including inputs" can be learned via backpropagation.

For 3: Actually, our original paper uses the neural network to update the vectors for edges (i.e., chemical bonds), but after publishing the paper I found that the performance was good without the edge update. In addition, the implementation of the edge update is little complicated and learning speed is slower.

Sorry to confuse you. I additionally described " this implementation is a simpler than the model proposed in our original paper (e.g., without edge vectors and their updates described in Eqs (5) and (6))" in the README.

**Comment by yvquanli** [comment]
Thanks for answering me so carefully.

It seems that I confuse you, for question 1 and 2. Sorry about that, actually, I mean:

For Q2: I believe, will it work better, if there were node features(such as valence, charge, aromatic, etc.) not only the type of atom element. I tried a GAT model with these features, and got some improvements.

For Q1: Just code for run_test.py , that mol and protein in, and interaction out.

**Comment by Dinxin** [comment]
@masashitsubaki Can you share the code with the edge update?

**Comment by yvquanli** [comment]
After thinking about it for a long time, I decided to say words sincerely
to you.
I got something wrong with my code when I check it, so the result can not
be trusted. I'm sorry and ashamed about that. That was a big day till now.
But I have some code to share with you, it's a GAT model with
batch-training for smile inputs. May you can try it.
With the DGL(deep graph lib), Graph NN may be easier to understand. Have a
good luck.

Dinxin <notifications@github.com> 于2019年5月23日周四 下午3:23写道：

**Comment by yvquanli** [comment]
Leave me an email address, or email me if needed.

**Comment by kiki-win** [comment]
> 感谢分享代码！
> 
> 我仔细阅读了代码，但发现了一些问题。
> 
> * 1 end2end 测试怎么样？end2end 的意思是，分子和蛋白质输入，相互作用输出。
> * 2 没有任何特征的分子输入，用GNN有意义吗？
> * 3 边缘特征在哪里？论文中有描述，但代码中没有行。

Hello, did you successfully use the trained model?
